# XGB Reg (Without Grid Search CV)

In [ ]:
import pandas as pd
import numpy as np
from sklearn.neighbors import NearestNeighbors
import xgboost as xgb
from sklearn.model_selection import train_test_split

data = pd.read_csv('../Dataset/District_Statewise_Well_with_coordinates.csv')


In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 689 entries, 0 to 688
Data columns (total 18 columns):
 #   Column                                                                Non-Null Count  Dtype  
---  ------                                                                --------------  -----  
 0   S.no.                                                                 689 non-null    int64  
 1   Name of State                                                         689 non-null    object 
 2   Name of District                                                      689 non-null    object 
 3   Recharge from rainfall During Monsoon Season                          684 non-null    float64
 4   Recharge from other sources During Monsoon Season                     684 non-null    float64
 5   Recharge from rainfall During Non Monsoon Season                      684 non-null    float64
 6   Recharge from other sources During Non Monsoon Season                 684 non-null    float64
 7  

In [48]:

target = "Total Natural Discharges"
#data = data.drop(columns=["S.no.", "Name of State", "Name of District", target])

In [6]:
data.head()

S.no.   Name of State Name of District  \
0      1  ANDHRA PRADESH        Anantapur   
1      2  ANDHRA PRADESH         Chittoor   
2      3  ANDHRA PRADESH    East Godavari   
3      4  ANDHRA PRADESH           Guntur   
4      5  ANDHRA PRADESH           Kadapa   

   Recharge from rainfall During Monsoon Season  \
0                                      89200.23   
1                                     115718.55   
2                                     104140.05   
3                                      52942.86   
4                                      93311.68   

   Recharge from other sources During Monsoon Season  \
0                                           46136.12   
1                                           32389.60   
2                                           95383.56   
3                                           57011.90   
4                                           15869.52   

   Recharge from rainfall During Non Monsoon Season  \
0                                           1013.97   
1                                           1204.19   
2                                           3714.55   
3                                           2547.96   
4                                           2048.53   

   Recharge from other sources During Non Monsoon Season  \
0                                           50415.31       
1                                           38028.60       
2                                           50847.53       
3                                           18800.39       
4                                           11177.61       

   Total Annual Ground Water Recharge  Total Natural Discharges  \
0                           186765.62                   9338.31   
1                           187340.94                   9367.06   
2                           254085.69                  12704.33   
3                           131303.10                   6565.15   
4                           122407.34                   6120.40   

   Annual Extractable Ground Water Resource  \
0                                 177427.31   
1                                 177973.88   
2                                 241381.36   
3                                 124737.95   
4                                 116286.94   

   Current Annual Ground Water Extraction For Irrigation  \
0                                          142953.85       
1                                           95256.50       
2                                           41688.32       
3                                           39174.72       
4                                           74888.06       

   Current Annual Ground Water Extraction For Domestic & Industrial Use  \
0                                           14884.94                      
1                                            9597.29                      
2                                            9418.15                      
3                                            8942.35                      
4                                            4974.42                      

   Total Current Annual Ground Water Extraction  \
0                                     157838.79   
1                                     104853.79   
2                                      51106.47   
3                                      48117.07   
4                                      79862.47   

   Annual GW Allocation for Domestic Use as on 2025  \
0                                          21623.75   
1                                          13528.83   
2                                           4226.85   
3                                          14159.10   
4                                           6110.25   

   Net Ground Water Availability for future use  \
0                                      59410.09   
1                                      80858.36   
2                                     193656.03   
3                                      79051.91   
4    

In [7]:
data = data.dropna()

In [8]:
data

S.no.   Name of State Name of District  \
0        1  ANDHRA PRADESH        Anantapur   
1        2  ANDHRA PRADESH         Chittoor   
2        3  ANDHRA PRADESH    East Godavari   
3        4  ANDHRA PRADESH           Guntur   
4        5  ANDHRA PRADESH           Kadapa   
..     ...             ...              ...   
684    685     LAKSHADWEEP        Kavaratti   
685    686     LAKSHADWEEP          Minicoy   
686    687      Puducherry       Puducherry   
687    688      Puducherry         Karaikal   
688    689      Puducherry             Mahe   

     Recharge from rainfall During Monsoon Season  \
0                                        89200.23   
1                                       115718.55   
2                                       104140.05   
3                                        52942.86   
4                                        93311.68   
..                                            ...   
684                                        124.90   
685                                        157.60   
686                                       7035.00   
687                                       1973.73   
688                                        245.45   

     Recharge from other sources During Monsoon Season  \
0                                             46136.12   
1                                             32389.60   
2                                             95383.56   
3                                             57011.90   
4                                             15869.52   
..                                                 ...   
684                                               0.00   
685                                               0.00   
686                                            2738.37   
687                                            4080.47   
688                                               0.00   

     Recharge from rainfall During Non Monsoon Season  \
0                                             1013.97   
1                                             1204.19   
2                                             3714.55   
3                                             2547.96   
4                                             2048.53   
..                                                ...   
684                                             22.70   
685                                             27.30   
686                                           1775.58   
687                                            209.22   
688                                             23.11   

     Recharge from other sources During Non Monsoon Season  \
0                                             50415.31       
1                                             38028.60       
2                                             50847.53       
3                                             18800.39       
4                                             11177.61       
..                                                 ...       
684                                               0.00       
685                                               0.00       
686                                            3671.63       
687                                             880.62       
688                                               0.00       

     Total Annual Ground Water Recharge  Total Natural Discharges  \
0                             186765.62                   9338.31   
1                             187340.94                   9367.06   
2                             254085.69                  12704.33   
3                             131303.10                   6565.15   
4                             122407.34                   6120.40   
..                                  ...                       ...   
684                              147.60                     97.30   
685                              184.90                    121.20   
686                            15220.58                

In [13]:

relevant_features = [
    'latitude', 'longitude',
    'Total Annual Ground Water Recharge', 
 
    'Annual Extractable Ground Water Resource',  
    'Total Current Annual Ground Water Extraction', 
    'Stage of Ground Water Extraction (%)' 
]
 

In [10]:

lat_long_data = data[['latitude', 'longitude']].values
nbrs = NearestNeighbors(n_neighbors=1, algorithm='ball_tree').fit(lat_long_data)


In [11]:
def find_nearest_lat_long(lat, long):
    input_coordinates = np.array([[lat, long]])
    
    distance, index = nbrs.kneighbors(input_coordinates)
    nearest_row = data.iloc[index[0][0]]
    return nearest_row

In [14]:

X = data[relevant_features]
y = data['Total Natural Discharges']


In [15]:

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

xg_reg = xgb.XGBRegressor(objective='reg:squarederror', colsample_bytree=0.3, learning_rate=0.1,
                          max_depth=5, alpha=10, n_estimators=100)
xg_reg.fit(X_train, y_train)

XGBRegressor(alpha=10, base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=0.3, device=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             gamma=None, grow_policy=None, importance_type=None,
             interaction_constraints=None, learning_rate=0.1, max_bin=None,
             max_cat_threshold=None, max_cat_to_onehot=None,
             max_delta_step=None, max_depth=5, max_leaves=None,
             min_child_weight=None, missing=nan, monotone_constraints=None,
             multi_strategy=None, n_estimators=100, n_jobs=None,
             num_parallel_tree=None, ...)

In [18]:
def predict_discharge_based_on_lat_long(lat, long):
    nearest_data = find_nearest_lat_long(lat, long)
    
    input_data = pd.DataFrame({
        'latitude': [nearest_data['latitude']],
        'longitude': [nearest_data['longitude']],
        'Total Annual Ground Water Recharge': [nearest_data['Total Annual Ground Water Recharge']],
        'Annual Extractable Ground Water Resource': [nearest_data['Annual Extractable Ground Water Resource']],
        'Total Current Annual Ground Water Extraction': [nearest_data['Total Current Annual Ground Water Extraction']],
        'Stage of Ground Water Extraction (%)': [nearest_data['Stage of Ground Water Extraction (%)']]
    })
    
    predicted_discharge = xg_reg.predict(input_data)
    return predicted_discharge[0]

In [26]:
# lat = 14.6818877
# long = 77.6005911

lat,long = 26.9124336,75.7872709
predicted_discharge = predict_discharge_based_on_lat_long(lat, long)

y_pred_xgb = xg_reg.predict(X_test)
print(f'Predicted Water Discharge: {predicted_discharge} cubic meters per day')


Predicted Water Discharge: 6323.87646484375 cubic meters per day


In [24]:
from sklearn.metrics import mean_squared_error
rmse_xgb = np.sqrt(mean_squared_error(y_test, y_pred_xgb))
print(f'XGBoost RMSE: {rmse_xgb}')

XGBoost RMSE: 3144.8923469522597


# Random Forest without GridSearch CV

In [12]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.neighbors import NearestNeighbors
import numpy as np

# Load the dataset
data = pd.read_csv('../Dataset/District_Statewise_Well_with_coordinates.csv')

# Drop rows with missing lat/lon or discharge data
data = data.dropna(subset=['latitude', 'longitude', 'Total Annual Ground Water Recharge'])

# Features for prediction (excluding Latitude, Longitude)
features = [
    'Recharge from rainfall During Monsoon Season', 
    'Recharge from other sources During Monsoon Season',
    'Recharge from rainfall During Non Monsoon Season', 
    'Recharge from other sources During Non Monsoon Season',
    'Total Annual Ground Water Recharge', 
    'Annual Extractable Ground Water Resource',
    'Current Annual Ground Water Extraction For Irrigation',
    'Current Annual Ground Water Extraction For Domestic & Industrial Use',
    'Total Current Annual Ground Water Extraction', 
    'Annual GW Allocation for Domestic Use as on 2025',
    'Net Ground Water Availability for future use', 
    'Stage of Ground Water Extraction (%)'
]

# Target for prediction
target = 'Total Natural Discharges'

# Prepare data for training
X = data[features]
y = data[target]

# Split the data into training and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Train a RandomForest model
model = RandomForestRegressor(n_estimators=100, random_state=42)
model.fit(X_train, y_train)

# Nearest neighbor search based on latitude and longitude
def find_nearest_district(lat, lon, data, n_neighbors=1):
    neigh = NearestNeighbors(n_neighbors=n_neighbors)
    coords = data[['latitude', 'longitude']].values.astype(float)
    neigh.fit(coords)
    dist, idx = neigh.kneighbors([[lat, lon]])
    nearest_district_index = idx[0][0]
    return nearest_district_index

# Function to predict water discharge based on latitude and longitude input
def predict_discharge(lat, lon):
    # Find the nearest district
    nearest_index = find_nearest_district(lat, lon, data)
    
    # Extract features of the nearest district
    nearest_district_features = data.iloc[nearest_index][features]
    
    # Predict the water discharge
    predicted_discharge = model.predict([nearest_district_features])
    
    return predicted_discharge[0]

# Example: Predict discharge for a given latitude and longitude
lat_input = 26.9124  # Example latitude (Jaipur)
lon_input = 75.7873  # Example longitude (Jaipur)

predicted_water_discharge = predict_discharge(lat_input, lon_input)
print(f"Predicted water discharge for lat {lat_input}, lon {lon_input}: {predicted_water_discharge}")


Predicted water discharge for lat 26.9124, lon 75.7873: 6810.115300000013


c:\Users\hp5cd\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(


In [13]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score, mean_absolute_percentage_error, explained_variance_score
import numpy as np

# Predict on the test set
y_pred = model.predict(X_test)

# Calculate error metrics
mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
rmse = np.sqrt(mse)
r2 = r2_score(y_test, y_pred)
mape = mean_absolute_percentage_error(y_test, y_pred)
evs = explained_variance_score(y_test, y_pred)

# Print the error metrics
print(f"Mean Absolute Error (MAE): {mae}")
print(f"Mean Squared Error (MSE): {mse}")
print(f"Root Mean Squared Error (RMSE): {rmse}")
print(f"R-squared (R²): {r2}")
print(f"Mean Absolute Percentage Error (MAPE): {mape}")
print(f"Explained Variance Score (EVS): {evs}")

Mean Absolute Error (MAE): 1183.9885320610692
Mean Squared Error (MSE): 4254831.440247318
Root Mean Squared Error (RMSE): 2062.7242763508934
R-squared (R²): 0.8381000508503955
Mean Absolute Percentage Error (MAPE): 0.2448500205459614
Explained Variance Score (EVS): 0.8381389466678766


# Random Forest with GridSearch CV(Best)

In [14]:
import pandas as pd
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.ensemble import RandomForestRegressor
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import NearestNeighbors
import numpy as np


data = pd.read_csv('../Dataset/District_Statewise_Well_with_coordinates.csv')


data = data.dropna(subset=['latitude', 'longitude', 'Total Annual Ground Water Recharge'])


features = [
    'Recharge from rainfall During Monsoon Season', 
    'Recharge from other sources During Monsoon Season',
    'Recharge from rainfall During Non Monsoon Season', 
    'Recharge from other sources During Non Monsoon Season',
    'Total Annual Ground Water Recharge', 
    'Annual Extractable Ground Water Resource',
    'Current Annual Ground Water Extraction For Irrigation',
    'Current Annual Ground Water Extraction For Domestic & Industrial Use',
    'Total Current Annual Ground Water Extraction', 
    'Annual GW Allocation for Domestic Use as on 2025',
    'Net Ground Water Availability for future use', 
    'Stage of Ground Water Extraction (%)'
]

target = 'Total Natural Discharges'

scaler = StandardScaler()
X_scaled = scaler.fit_transform(data[features])

X_train, X_test, y_train, y_test = train_test_split(X_scaled, data[target], test_size=0.2, random_state=42)

rf_model = RandomForestRegressor(random_state=42)
param_grid = {
    'n_estimators': [100, 200],
    'max_depth': [5, 10, None],
    'min_samples_split': [2, 5, 10]
}

grid_search = GridSearchCV(rf_model, param_grid, cv=5, scoring='neg_mean_squared_error')
grid_search.fit(X_train, y_train)

best_rf_model = grid_search.best_estimator_




In [15]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 652 entries, 0 to 688
Data columns (total 18 columns):
 #   Column                                                                Non-Null Count  Dtype  
---  ------                                                                --------------  -----  
 0   S.no.                                                                 652 non-null    int64  
 1   Name of State                                                         652 non-null    object 
 2   Name of District                                                      652 non-null    object 
 3   Recharge from rainfall During Monsoon Season                          652 non-null    float64
 4   Recharge from other sources During Monsoon Season                     652 non-null    float64
 5   Recharge from rainfall During Non Monsoon Season                      652 non-null    float64
 6   Recharge from other sources During Non Monsoon Season                 652 non-null    float64
 7   Tota

In [10]:
def find_nearest_district(lat, lon, data, n_neighbors=1):
    neigh = NearestNeighbors(n_neighbors=n_neighbors)
    coords = data[['latitude', 'longitude']].values.astype(float)
    neigh.fit(coords)
    dist, idx = neigh.kneighbors([[lat, lon]])
    nearest_district_index = idx[0][0]
    return nearest_district_index

def predict_discharge(lat, lon):
    nearest_index = find_nearest_district(lat, lon, data)
    
    nearest_district_features = data.iloc[nearest_index][features].values
    nearest_district_features_scaled = scaler.transform([nearest_district_features])
    
    predicted_discharge = best_rf_model.predict(nearest_district_features_scaled)
    
    return predicted_discharge[0]

lat_input = 26.9124  
lon_input = 75.7873  

predicted_water_discharge = predict_discharge(lat_input, lon_input)
print(f"Predicted water discharge for lat {lat_input}, lon {lon_input}: {predicted_water_discharge}")

Predicted water discharge for lat 26.9124, lon 75.7873: 6649.4957711182105


c:\Users\hp5cd\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


In [11]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score, mean_absolute_percentage_error, explained_variance_score
import numpy as np

# Predict on the test set
y_pred = best_rf_model.predict(X_test)

# Calculate error metrics
mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
rmse = np.sqrt(mse)
r2 = r2_score(y_test, y_pred)
mape = mean_absolute_percentage_error(y_test, y_pred)
evs = explained_variance_score(y_test, y_pred)

# Print the error metrics
print(f"Mean Absolute Error (MAE): {mae}")
print(f"Mean Squared Error (MSE): {mse}")
print(f"Root Mean Squared Error (RMSE): {rmse}")
print(f"R-squared (R²): {r2}")
print(f"Mean Absolute Percentage Error (MAPE): {mape}")
print(f"Explained Variance Score (EVS): {evs}")

Mean Absolute Error (MAE): 1163.7505474857492
Mean Squared Error (MSE): 3959336.744198204
Root Mean Squared Error (RMSE): 1989.8082179441826
R-squared (R²): 0.849343874944529
Mean Absolute Percentage Error (MAPE): 0.24318345172312944
Explained Variance Score (EVS): 0.8493540512809499


# XgBoost with Grid Search CV and limited features

In [6]:
import pandas as pd
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import NearestNeighbors
import numpy as np


data = pd.read_csv('../Dataset/District_Statewise_Well_with_coordinates.csv')


data = data.dropna(subset=['latitude', 'longitude', 'Total Annual Ground Water Recharge'])


features = [
    'Recharge from rainfall During Monsoon Season', 
    'Recharge from rainfall During Non Monsoon Season', 
    'Total Annual Ground Water Recharge', 
    'Net Ground Water Availability for future use', 
    'Stage of Ground Water Extraction (%)'
]


target = 'Total Natural Discharges'


X = data[features]
y = data[target]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Scale the data (helpful for gradient boosting models)
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# GradientBoosting model with hyperparameter tuning
param_grid = {
    'n_estimators': [100, 200],
    'learning_rate': [0.05, 0.1, 0.2],
    'max_depth': [3, 5, 7]
}
model = GradientBoostingRegressor(random_state=42)
grid_search = GridSearchCV(model, param_grid, cv=5, scoring='neg_mean_squared_error', n_jobs=-1)
grid_search.fit(X_train_scaled, y_train)


best_model = grid_search.best_estimator_


def find_nearest_district(lat, lon, data, n_neighbors=1):
    neigh = NearestNeighbors(n_neighbors=n_neighbors)
    coords = data[['latitude', 'longitude']].values.astype(float)
    neigh.fit(coords)
    dist, idx = neigh.kneighbors([[lat, lon]])
    nearest_district_index = idx[0][0]
    return nearest_district_index
1

def predict_discharge(lat, lon):
    nearest_index = find_nearest_district(lat, lon, data)
    
    
    nearest_district_features = data.iloc[nearest_index][features].values.reshape(1, -1)
    nearest_district_features_scaled = scaler.transform(nearest_district_features)
    
    
    predicted_discharge = best_model.predict(nearest_district_features_scaled)
    
    return predicted_discharge[0]


lat_input = 25.5940947  
lon_input = 85.1375645

predicted_water_discharge = predict_discharge(lat_input, lon_input)
print(f"Predicted water discharge for lat {lat_input}, lon {lon_input}: {predicted_water_discharge}")


Predicted water discharge for lat 25.5940947, lon 85.1375645: 7155.964702707621


c:\Users\hp5cd\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


In [7]:
import pickle

# Create a dictionary to store the model, scaler, and features
model_artifacts = {
    'model': predict_discharge,
    'scaler': scaler,
    'features': features,
    'data': data[['latitude', 'longitude']]  # Only latitude and longitude for nearest neighbor search
}

# Save the model artifacts to a pickle file
with open('water_discharge_prediction.pkl', 'wb') as file:
    pickle.dump(model_artifacts, file)

In [32]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score, mean_absolute_percentage_error, explained_variance_score
import numpy as np

y_pred = best_model.predict(X_test_scaled)

# Calculate error metrics
mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
rmse = np.sqrt(mse)
r2 = r2_score(y_test, y_pred)
mape = mean_absolute_percentage_error(y_test, y_pred)
evs = explained_variance_score(y_test, y_pred)


print(f"Mean Absolute Error (MAE): {mae}")
print(f"Mean Squared Error (MSE): {mse}")
print(f"Root Mean Squared Error (RMSE): {rmse}")
print(f"R-squared (R²): {r2}")
print(f"Mean Absolute Percentage Error (MAPE): {mape}")
print(f"Explained Variance Score (EVS): {evs}")


Mean Absolute Error (MAE): 1641.5929831599954
Mean Squared Error (MSE): 8559899.133827403
Root Mean Squared Error (RMSE): 2925.7305299407535
R-squared (R²): 0.6742885696050404
Mean Absolute Percentage Error (MAPE): 0.3625209654338928
Explained Variance Score (EVS): 0.6778049526639105


# usisng 2 input


import pandas as pd
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.ensemble import RandomForestRegressor
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import NearestNeighbors
import numpy as np


data = pd.read_csv('../Dataset/District_Statewise_Well_with_coordinates.csv')


#data = data.dropna(subset=['latitude', 'longitude', 'Total Annual Ground Water Recharge'])


<!-- features = [
    'Recharge from rainfall During Monsoon Season', 
    'Recharge from other sources During Monsoon Season',
    'Recharge from rainfall During Non Monsoon Season', 
    'Recharge from other sources During Non Monsoon Season',
    'Total Annual Ground Water Recharge', 
    'Annual Extractable Ground Water Resource',
    'Current Annual Ground Water Extraction For Irrigation',
    'Current Annual Ground Water Extraction For Domestic & Industrial Use',
    'Total Current Annual Ground Water Extraction', 
    'Annual GW Allocation for Domestic Use as on 2025',
    'Net Ground Water Availability for future use', 
    'Stage of Ground Water Extraction (%)'
] -->
X = df_clean[['latitude', 'longitude']]
target = 'Total Natural Discharges'

scaler = StandardScaler()
X_scaled = scaler.fit_transform(data[features])

X_train, X_test, y_train, y_test = train_test_split(X_scaled, data[target], test_size=0.2, random_state=42)

rf_model = RandomForestRegressor(random_state=42)
param_grid = {
    'n_estimators': [100, 200],
    'max_depth': [5, 10, None],
    'min_samples_split': [2, 5, 10]
}

grid_search = GridSearchCV(rf_model, param_grid, cv=5, scoring='neg_mean_squared_error')
grid_search.fit(X_train, y_train)

best_rf_model = grid_search.best_estimator_




In [3]:
import pandas as pd
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.ensemble import RandomForestRegressor
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.neighbors import NearestNeighbors
import numpy as np

# Load data
data = pd.read_csv('../Dataset/District_Statewise_Well_with_coordinates.csv')

# Drop rows with missing values
target = 'Total Natural Discharges'
data = data.dropna(subset=['latitude', 'longitude', target])

# Feature selection
X = data[['latitude', 'longitude']]
y = data[target]

# Train-test split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Scaling
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# RandomForest and hyperparameter tuning
rf_model = RandomForestRegressor(random_state=42)
param_grid = {
    'n_estimators': [100, 200, 300],
    'max_depth': [5, 10, 20, None],
    'min_samples_split': [2, 5, 10],
    'min_samples_leaf': [1, 2, 4],
    'bootstrap': [True, False]
}

grid_search = GridSearchCV(rf_model, param_grid, cv=5, scoring='neg_mean_squared_error')
grid_search.fit(X_train, y_train)
best_rf_model = grid_search.best_estimator_

# Model evaluation
y_pred = best_rf_model.predict(X_test)
mse = mean_squared_error(y_test, y_pred)
rmse = np.sqrt(mse)
r2 = r2_score(y_test, y_pred)

print(f"Best Model Parameters: {grid_search.best_params_}")
print(f"RMSE: {rmse}")
print(f"R² Score: {r2}")

# Nearest neighbors (optional)
nn = NearestNeighbors(n_neighbors=3)
nn.fit(X)
distances, indices = nn.kneighbors(X_test)
print(f"Nearest neighbors' indices for test wells: {indices}")


Best Model Parameters: {'bootstrap': True, 'max_depth': 10, 'min_samples_leaf': 1, 'min_samples_split': 10, 'n_estimators': 300}
RMSE: 3985.8672856297912
R² Score: 0.39548090835690297
Nearest neighbors' indices for test wells: [[476  23 644]
 [476  23 644]
 [476  23 644]
 [476  23 644]
 [476  23 135]
 [476  23 644]
 [476  23 135]
 [476  23 135]
 [476  23 644]
 [476  23 135]
 [476  23 135]
 [476  23 135]
 [476  23 135]
 [476  23 135]
 [476  23 644]
 [476  23 135]
 [476  23 135]
 [476  23 135]
 [476  23 135]
 [476  23 135]
 [476  23 135]
 [476  23 135]
 [476  23 135]
 [476  23 135]
 [476  23 135]
 [476  23 135]
 [476  23 644]
 [476  23 135]
 [476  23 135]
 [476  23 135]
 [476  23 644]
 [476  23 135]
 [476  23 135]
 [476  23 135]
 [476  23 135]
 [476  23 135]
 [476  23 135]
 [476  23 135]
 [476  23 135]
 [476  23 135]
 [476  23 135]
 [476  23 135]
 [476  23 644]
 [476  23 135]
 [476  23 135]
 [476  23 135]
 [476  23 135]
 [476  23 135]
 [476  23 644]
 [476  23 135]
 [476  23 644]
 [476  2

c:\Users\hp5cd\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but NearestNeighbors was fitted with feature names
  warnings.warn(
